language: php

php:
  - 5.5
  - 5.6

# Update composer
before_install:
  - travis_retry composer self-update && composer --version

# install composer dependencies & optimize the autoload
install:
  - travis_retry composer install --prefer-dist --no-interaction
  - travis_retry composer dump-autoload --optimize

branches:
  only: master

# don't continue the build process if it fails
matrix:
  fast_finish: true

# don't send me a notification
notifications:
    on_success: never
    on_failure: never