runtime: php55
api_version: 1
instance_class: B8
skip_files:
  - ^(.*/)?.*/.git/.*$
basic_scaling:
  max_instances: 25
  idle_timeout: 60m
handlers:
- url: /
  script: index.php

- url: /.*
  script: index.php